import { Hono } from 'hono'
import { cors } from 'hono/cors'
import { serveStatic } from 'hono/cloudflare-workers'
import { renderer } from './renderer'

const app = new Hono()

// CORS 설정
app.use('/api/*', cors())

// 정적 파일 서빙 (public/static/ -> /static/*)
app.use('/static/*', serveStatic({ root: './public' }))

// 렌더러 적용
app.use(renderer)

// API Routes
app.get('/api/agents', (c) => {
  return c.json({
    agents: [
      {
        id: 'financial-advisor',
        name: '금융 컨설팅 에이전트',
        category: '재무관리',
        description: '경영·재무·보험·자산관리 통합 컨설팅',
        prompt: `당신은 박사급 금융 컨설턴트입니다. 경영, 재무, 보험, 자산관리의 통합적 시너지를 고려하여 조언합니다.`,
        tags: ['금융', '컨설팅', '자산관리', '보험'],
        author: '한국인프라연구원(주)',
        usage: 156
      },
      {
        id: 'blockchain-expert',
        name: '블록체인 & STO 전문가',
        category: '대체금융',
        description: '블록체인 구조, 마이닝, STO 혁신증권 전문 에이전트',
        prompt: `블록체인 기술과 STO(Security Token Offering) 전문가로서 혁신적인 증권 솔루션을 제안합니다.`,
        tags: ['블록체인', 'STO', '암호화폐', '혁신증권'],
        author: '한국인프라연구원(주)',
        usage: 89
      },
      {
        id: 'renewable-energy',
        name: '신재생에너지 & 수전해 전문가',
        category: '에너지',
        description: '수전해 기술 및 신재생에너지 사업 전문 에이전트',
        prompt: `수소 추출 수전해 기술과 신재생에너지 분야의 전문가로서 기술적, 사업적 조언을 제공합니다.`,
        tags: ['수전해', '수소', '신재생에너지', '그린테크'],
        author: '한국인프라연구원(주)',
        usage: 67
      },
      {
        id: 'startup-accelerator',
        name: '스타트업 투자 & 액셀러레이터',
        category: '투자',
        description: '스타트업 투자 및 액셀러레이팅 전문 에이전트',
        prompt: `스타트업 투자자이자 액셀러레이터로서 사업 모델 검증, 투자 유치 전략을 제안합니다.`,
        tags: ['스타트업', '투자', '액셀러레이팅', '사업모델'],
        author: '한국인프라연구원(주)',
        usage: 134
      },
      {
        id: 'tax-optimization',
        name: '절세 & 세무 최적화 전문가',
        category: '세무',
        description: 'VIP 고객을 위한 절세 및 세무 최적화 에이전트',
        prompt: `세무 최적화 전문가로서 합법적이고 효과적인 절세 전략을 제안합니다.`,
        tags: ['절세', '세무', '세금최적화', 'VIP'],
        author: '한국인프라연구원(주)',
        usage: 203
      }
    ]
  })
})

app.get('/api/agent/:id', (c) => {
  const id = c.req.param('id')
  // 에이전트 상세 정보 반환
  return c.json({
    id,
    message: `에이전트 ${id}의 상세 정보입니다.`
  })
})

app.post('/api/agents', async (c) => {
  const body = await c.req.json()
  
  // 새 에이전트 생성 로직
  const newAgent = {
    id: `custom-${Date.now()}`,
    name: body.name,
    category: body.category,
    description: body.description,
    prompt: body.prompt,
    tags: body.tags || [],
    author: '사용자 생성',
    usage: 0,
    created: new Date().toISOString()
  }
  
  return c.json({
    success: true,
    agent: newAgent,
    message: '새로운 에이전트가 생성되었습니다.'
  })
})

app.get('/api/export/:id/:format', (c) => {
  const id = c.req.param('id')
  const format = c.req.param('format')
  
  // Cursor IDE 통합을 위한 export 포맷
  if (format === 'cursor') {
    return c.json({
      format: 'cursor-rules',
      content: `// Vibe Agent: ${id}
// Generated by Vibe Agent Builder
// 한국인프라연구원(주) - infrastructure@kakao.com

You are a specialized AI agent for ${id}.
Follow these guidelines and maintain professional standards.`,
      instructions: 'Cursor IDE의 .cursor-rules 파일에 복사하여 사용하세요.'
    })
  }
  
  return c.json({ error: '지원하지 않는 포맷입니다.' })
})

// 메인 페이지
app.get('/', (c) => {
  return c.render(
    <div>
      <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
        <div className="container mx-auto px-4 py-8">
          <header className="text-center mb-12">
            <h1 className="text-5xl font-bold text-gray-800 mb-4">
              🤖 Vibe Agent Builder
            </h1>
            <p className="text-xl text-gray-600 mb-2">
              Cursor IDE용 맞춤형 AI 에이전트 생성 도구
            </p>
            <p className="text-sm text-gray-500">
              한국인프라연구원(주) | infrastructure@kakao.com | 010-9143-0800
            </p>
          </header>

          <div className="grid md:grid-cols-3 gap-8 mb-12">
            <div className="bg-white p-6 rounded-xl shadow-lg">
              <div className="text-3xl mb-4">💡</div>
              <h3 className="text-xl font-semibold mb-3">스마트 에이전트 생성</h3>
              <p className="text-gray-600">
                박사급 전문가의 도메인 지식을 바탕으로 한 AI 에이전트를 쉽게 생성하세요.
              </p>
            </div>
            
            <div className="bg-white p-6 rounded-xl shadow-lg">
              <div className="text-3xl mb-4">⚡</div>
              <h3 className="text-xl font-semibold mb-3">Cursor IDE 통합</h3>
              <p className="text-gray-600">
                생성된 에이전트를 Cursor IDE에 바로 적용하여 개발 효율성을 극대화하세요.
              </p>
            </div>
            
            <div className="bg-white p-6 rounded-xl shadow-lg">
              <div className="text-3xl mb-4">🎯</div>
              <h3 className="text-xl font-sem트용semibold mb-3">전문 도메인 특화</h3>
              <p className="text-gray-600">
                금융, 블록체인, 신재생에너지 등 전문 분야에 특화된 에이전트를 제공합니다.
              </p>
            </div>
          </div>

          <div className="text-center">
            <button 
              id="startBtn"
              className="bg-blue-600 text-white px-8 py-4 rounded-lg text-lg font-semibold hover:bg-blue-700 transition duration-200 shadow-lg"
            >
              🚀 에이전트 빌더 시작하기
            </button>
          </div>
        </div>
      </div>

      <div id="agentBuilder" className="hidden min-h-screen bg-gray-50 py-8">
        <div className="container mx-auto px-4">
          <div className="max-w-6xl mx-auto">
            <h2 className="text-3xl font-bold text-center mb-8">AI 에이전트 생성 & 관리</h2>
            
            <div className="grid lg:grid-cols-2 gap-8">
              {/* 왼쪽: 에이전트 목록 */}
              <div className="bg-white rounded-xl shadow-lg p-6">
                <div className="flex justify-between items-center mb-6">
                  <h3 className="text-xl font-semibold">전문 에이전트 라이브러리</h3>
                  <button id="refreshBtn" className="text-blue-600 hover:text-blue-800">
                    🔄 새로고침
                  </button>
                </div>
                <div id="agentList" className="space-y-4">
                  {/* 에이전트 목록이 여기에 동적으로 로드됩니다 */}
                </div>
              </div>

              {/* 오른쪽: 에이전트 생성/편집 */}
              <div className="bg-white rounded-xl shadow-lg p-6">
                <h3 className="text-xl font-semibold mb-6">새 에이전트 생성</h3>
                <form id="agentForm" className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium mb-2">에이전트 이름</label>
                    <input 
                      type="text" 
                      id="agentName"
                      className="w-full p-3 border rounded-lg focus:ring-2 focus:ring-blue-500"
                      placeholder="예: 블록체인 코딩 전문가"
                    />
                  </div>
                  
                  <div>
                    <label className="block text-sm font-medium mb-2">카테고리</label>
                    <select 
                      id="agentCategory"
                      className="w-full p-3 border rounded-lg focus:ring-2 focus:ring-blue-500"
                    >
                      <option value="">카테고리 선택</option>
                      <option value="재무관리">재무관리</option>
                      <option value="대체금융">대체금융</option>
                      <option value="에너지">에너지</option>
                      <option value="투자">투자</option>
                      <option value="세무">세무</option>
                      <option value="개발">개발</option>
                      <option value="기타">기타</option>
                    </select>
                  </div>
                  
                  <div>
                    <label className="block text-sm font-medium mb-2">설명</label>
                    <textarea 
                      id="agentDescription"
                      className="w-full p-3 border rounded-lg focus:ring-2 focus:ring-blue-500"
                      rows="3"
                      placeholder="에이전트의 역할과 특징을 설명하세요"
                    ></textarea>
                  </div>
                  
                  <div>
                    <label className="block text-sm font-medium mb-2">시스템 프롬프트</label>
                    <textarea 
                      id="agentPrompt"
                      className="w-full p-3 border rounded-lg focus:ring-2 focus:ring-blue-500 font-mono text-sm"
                      rows="8"
                      placeholder="당신은 전문적인 AI 어시스턴트입니다..."
                    ></textarea>
                  </div>
                  
                  <div>
                    <label className="block text-sm font-medium mb-2">태그 (쉼표로 구분)</label>
                    <input 
                      type="text" 
                      id="agentTags"
                      className="w-full p-3 border rounded-lg focus:ring-2 focus:ring-blue-500"
                      placeholder="예: 블록체인, 스마트컨트랙트, DeFi"
                    />
                  </div>
                  
                  <button 
                    type="submit"
                    className="w-full bg-green-600 text-white py-3 rounded-lg font-semibold hover:bg-green-700 transition"
                  >
                    ✨ 에이전트 생성
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>

      <script src="/static/app.js"></script>
    </div>
  )
})

export default app